services:
  - type: web
    name: smart-health-diagnosis
    env: python
    plan: free
    buildCommand: poetry install --no-dev
    startCommand: poetry run gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
